### ISSUE TITLE
Is the project stopped?

### ISSUE THREAD

**Issue by mafshin** [bridgedotnet/Granular#27]
Once I saw GranularPad, I was amazed that the dream of having XAML in web is in front of my eyes.

I already tracked the following projects
- https://github.com/wsick/Fayde (With similar approach rendering into Canvas)
- https://github.com/Perspex/Perspex (Cross-platform desktop XAML)
- http://cshtml5.com 

but I found GranularPad the most attractive one but unfortunately I see no updates since 7 months ago.

Is it completely stopped or will get new updates in future?

**Comment by Cyral** [comment]
There is some more recent work from February on the development branch

**Comment by yuvaltz** [comment]
Thanks for your kind words!

As @Cyral said, I made the mistake of pushing to a development branch rather than the master branch, so the default page in github doesn't seem very much alive, but I'm still working on it (I rewrote the dispatcher, implemented layout and render transforms, and made some other optimizations).
I have a long list of tasks and features planned, and I'm always trying to find more time to work on it (during weekends, evening, my commute to work..), it's not that much time, so anyone who can contribute could make a big difference here.

I do understand that this is not the easiest project to get in to, as it requires a deep understanding of WPF (and some understanding of what I did there), but from my experience it's not as hard as it first seems, and I'll be more than happy to help anyone to get into it and start implementing features.
Also, beside features, contribution can be done in other areas such as setting up a CI, extending the wiki and generally making this project look more appealing for developers.

I believe that with the right amount of contributors this project could become a viable solution in not such a long time.

**Comment by mafshin** [comment]
@yuvaltz  I appreciate the effort you put on this, let met review the code and play with it and definitely I'll be a contributor to the extent of my knowledge.

**Comment by yuvaltz** [comment]
Great :)
I'll do my best to help

**Comment by hcasado** [comment]
I'm planning a Silverlight to Javscript migration including Granular as an option.

**Comment by geoffreymcgill** [comment]
> Is it completely stopped or will get new updates in future?

[Granular](https://github.com/bridgedotnet/Granular) has found a new home with [Bridge.NET](https://bridge.net). Granular will see some updates, but it will take a little bit of time to get up to speed.
