### ISSUE TITLE
Web requests

### ISSUE THREAD

**Issue by XspeedPL** [bridgedotnet/Granular#47]
Hello,
Is there any way to make web requests with Granular?
WebClient and WebRequest classes seem to not be available.
Basically I need to connect to a WCF service, but it can work with standard GET web requests too.

**Comment by AndreyChechel** [comment]
Hi @XspeedPL,

You can use Ajax requests for that, see the sample by the link below:
https://deck.net/webservice

**Comment by XspeedPL** [comment]
Thanks for the reply.
How can I reference the jQuery class in the WPF project though?

**Comment by AndreyChechel** [comment]
Try installing **Retyped.jquery** package for that:
https://retyped.com/?q=jquery#search
https://www.nuget.org/packages/retyped.jquery

Since Retyped emits static classes instead of namespaces, you might want to use:
```
using static Retyped.jquery;
```

**Comment by XspeedPL** [comment]
Installing any Bridge-related package removes references to mscorlib.dll, I can't use that

**Comment by AndreyChechel** [comment]
Correct, in order to support compilation of the project both as WPF app and Granular/Bridge app - Retyped packages need to be installed in `YourWpfApplication.Web` or another Bridge project. You'll likely need to setup code sharing between Bridge and non-Bridge projects.

I've prepared a simple project demonstrating that idea:
https://github.com/Retyped/Demos/tree/master/GranularDemo

The solution structure:
1. **GranularDemo** - a regular WPF project.
1. **GranularDemo.Shared** - a Bridge project declaring interfaces for classes containing Bridge/Retyped logic.
1. **GranularDemo.Web** - a Granular/Bridge project referring to Retyped packages and implementing required logic. 

Points of interest:
1. **GranularDemo** includes [interfaces](https://github.com/Retyped/Demos/tree/ec0858f1bb2e8404a2e4b882adaf81e6812dbdac/GranularDemo/GranularDemo.Shared/Interfaces) from **GranularDemo.Shared** added as [linked files](https://github.com/Retyped/Demos/blob/66373b9fb9eecbd81089658542c472d70b7fa13a/GranularDemo/GranularDemo/GranularDemo.csproj#L58-L60). To do that, just drag and drop folder/file while holding `Alt`.
1. **GranularDemo** declares [Resolver](https://github.com/Retyped/Demos/blob/ec0858f1bb2e8404a2e4b882adaf81e6812dbdac/GranularDemo/GranularDemo/Shared/Resolver.cs) type allowing to register/resolve interface implementations. It also could be helpful if you need to have different logic in native WPF app and in a Web version of that app.
1. **Resolver** uses [a preprocessor directive](https://github.com/Retyped/Demos/blob/ec0858f1bb2e8404a2e4b882adaf81e6812dbdac/GranularDemo/GranularDemo/Shared/Resolver.cs#L10-L16) to check whether `Granular` symbol is defined. That symbol is  [defined](https://github.com/Retyped/Demos/blob/ec0858f1bb2e8404a2e4b882adaf81e6812dbdac/GranularDemo/GranularDemo.Web/GranularDemo.Web.csproj#L22) in **GranularDemo.Web** project. So the registration will take place only when converting to Web app (the reason - we can't refer Bridge logic in regular WPF app).
1. Then **Resolver** could be used to get implementation of a shared interface like [here](https://github.com/Retyped/Demos/blob/ec0858f1bb2e8404a2e4b882adaf81e6812dbdac/GranularDemo/GranularDemo/MainWindow.xaml.cs#L22).
1. **GranularDemo.Shared** project [refers](https://github.com/Retyped/Demos/blob/ec0858f1bb2e8404a2e4b882adaf81e6812dbdac/GranularDemo/GranularDemo.Shared/packages.config#L3) **Bridge.Core** package to be compatible with **GranularDemo.Web**.
1. **GranularDemo.Web** [refers](https://github.com/Retyped/Demos/blob/ec0858f1bb2e8404a2e4b882adaf81e6812dbdac/GranularDemo/GranularDemo.Web/GranularDemo.Web.csproj#L92-L95) **GranularDemo.Shared** project and [Retyped packages](https://github.com/Retyped/Demos/blob/ec0858f1bb2e8404a2e4b882adaf81e6812dbdac/GranularDemo/GranularDemo.Web/packages.config#L7-L10).
1. **GranularDemo.Web** implements the shared interface(s) [here](https://github.com/Retyped/Demos/tree/ec0858f1bb2e8404a2e4b882adaf81e6812dbdac/GranularDemo/GranularDemo.Web/Shared/Internal).
1. Usage of **Retyped.jquery** requires the corresponding script to be located in the `dist` folder and to be added to [the page](https://github.com/Retyped/Demos/blob/ec0858f1bb2e8404a2e4b882adaf81e6812dbdac/GranularDemo/GranularDemo.Web/dist/index.html#L22).
1. Pay attention that installed Retyped packages versions are not the latest ones. The reason - Granular uses an old version of Bridge (`16.3.2`), so to make it conformed Retyped packages referring similar **Bridge.Core** version were selected.

Hope that helps.

**Comment by XspeedPL** [comment]
Ahhh, somehow the thought about using preprocessor directives didn't occur to me!
Thanks a lot :)
